[env:seeed_solar_node]
custom_meshtastic_hw_model = 95
custom_meshtastic_hw_model_slug = SEEED_SOLAR_NODE
custom_meshtastic_architecture = nrf52840
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = Seeed SenseCAP Solar Node
custom_meshtastic_images = seeed_solar.svg
custom_meshtastic_tags = Seeed

; NAVARICO: exclusiones y flags incorporados desde el repo Seed (evitan compilar sensores no montados)
lib_ldf_mode = deep+
lib_ignore =
  BluetoothOTA
  lvgl
  SparkFun MMC5983MA Magnetometer Arduino Library
  SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library
  SparkFun Qwiic Scale NAU7802 Arduino Library
board = seeed_solar_node
extends = nrf52840_base
;board_level = extra
build_flags = ${nrf52840_base.build_flags} 
  -I variants/nrf52840/seeed_solar_node 
  -D SEEED_SOLAR_NODE 
  -DMESHTASTIC_EXCLUDE_MAGNETOMETER=1
  -DMESHTASTIC_EXCLUDE_ACCELEROMETER=1
  -I src/platform/nrf52/softdevice
  -I src/platform/nrf52/softdevice/nrf52
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/seeed_solar_node>
debug_tool = jlink
